apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kmaster
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: tasktracker-service
    servicePort: 3000
