apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
